@PORT=8812
@HOST=localhost

###
GET http://{{HOST}}:{{PORT}}/export/status HTTP/1.1


###
POST http://{{HOST}}:{{PORT}}/export/candidate-management HTTP/1.1
content-type: application/json

{
    "vacancy_id": 333438,
    "email": "tkg.dev@yopmail.com"

}

###
POST http://{{HOST}}:{{PORT}}/export/candidate-pool HTTP/1.1
content-type: application/json

{
    "vacancy_id": null,
    "email": "tkg.dev@yopmail.com",
    "start_date": "2025-11-10T04:10:57.275Z",
    "end_date": "2025-11-24T04:10:57.275Z"
}



###
GET http://{{HOST}}:{{PORT}}/healthz HTTP/1.1






